void _puts_recursion(char *s);
int _putchar(char c);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int natural_square(int x, int y);
int is_prime_number(int n);
int pnumber(int x, int n);
int is_palindrome(char *s);
int _scan(char *c, char *d);
int is_palindrome(char *s);
